config/routes.rb
Rails.application.routes.draw do
  resources :emplprojs
  resources :projects do
    member do
      get :activate
    end
  end
  resources :empls do
    collection do
      get :search
    end
    member do
      get :change_depart
    end
  end
 
  resources :departs
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/emplproj.rb
class Emplproj < ActiveRecord::Base
  belongs_to :empl
  belongs_to :project, inverse_of: :emplprojs

  validates :empl_id, presence: true
  validates :project, presence: true
end

app/controllers/emplprojs_controller.rb
class EmplprojsController < ApplicationController
  before_action :set_emplproj, only: [:show, :edit, :update, :destroy]

  # GET /emplprojs
  # GET /emplprojs.json
  def index
    @emplprojs = Emplproj.all
  end

  # GET /emplprojs/1
  # GET /emplprojs/1.json
  def show
  end

  # GET /emplprojs/new
  def new
    @emplproj = Emplproj.new
  end

  # GET /emplprojs/1/edit
  def edit
  end

  # POST /emplprojs
  # POST /emplprojs.json
  def create
    @emplproj = Emplproj.new(emplproj_params)

    respond_to do |format|
      if @emplproj.save
        format.html { redirect_to @emplproj, notice: 'Emplproj was successfully created.' }
        format.json { render :show, status: :created, location: @emplproj }
      else
        format.html { render :new }
        format.json { render json: @emplproj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emplprojs/1
  # PATCH/PUT /emplprojs/1.json
  def update
    respond_to do |format|
      if @emplproj.update(emplproj_params)
        format.html { redirect_to @emplproj, notice: 'Emplproj was successfully updated.' }
        format.json { render :show, status: :ok, location: @emplproj }
      else
        format.html { render :edit }
        format.json { render json: @emplproj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emplprojs/1
  # DELETE /emplprojs/1.json
  def destroy
    @emplproj.destroy
    respond_to do |format|
      format.html { redirect_to emplprojs_url, notice: 'Emplproj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emplproj
      @emplproj = Emplproj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emplproj_params
      params.require(:emplproj).permit(:empl_id, :project_id)
    end
end

app/helpers/emplprojs_helper.rb
module EmplprojsHelper
  # nested_start
  def link_to_add_empl(form, project)
    # Создаём новый объект. Аналог build в ранних примерах
    new_object = Emplproj.new()
    # Нам нужна nested-форма. В момент создания ссылки её ещё нет. Создадим её
    # Все role_users в форме имеют свой номер
    # Мы его пока заменям на фразу new_ru
    fields = form.fields_for(:emplprojs, new_object,
      :child_index => 'new_empl') do |fr|
      render('projects/one_empl_form', fr: fr, i: 'Новый')
    end
    # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
    link_to(?#, class: 'btn btn-info',
        id: 'add_empl_link', data: {content: "#{fields}"}) do
      fa_icon("plus") + " Новый сотрудник"
    end
  end

  def link_to_remove_empl(form)
    # При удалении nested-конструкции. Она реально не удаляется
    # Соответствующий html-блок скрывается
    # При этом выставляется значение специального поля _destroy
    # По этому поля rails понимает, что связь надо удалить
    form.hidden_field(:_destroy, class: 'remove_fields') +
        # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
        link_to(?#, class: 'remove_fields remove_empl') do 
      fa_icon('times', title: 'Удалить сотрудника') + ' Удалить'
    end
  end
  def project_options()
    Project.all.collect {|p| [p.p_name, p.id]}
  end
  # nested_finish
end

app/views/emplprojs/_form.html.haml
= form_for @emplproj do |f|
  - if @emplproj.errors.any?
    #error_explanation
      %h2= "#{pluralize(@emplproj.errors.count, "error")} prohibited this emplproj from being saved:"
      %ul
        - @emplproj.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :empl
    = f.text_field :empl
  .field
    = f.label :project
    = f.text_field :project
  .actions
    = f.submit 'Save'

app/views/emplprojs/edit.html.haml
%h1 Editing emplproj

= render 'form'

= link_to 'Show', @emplproj
\|
= link_to 'Back', emplprojs_path

app/views/emplprojs/index.html.haml
%h1 Listing emplprojs

%table
  %thead
    %tr
      %th Empl
      %th Project
      %th
      %th
      %th

  %tbody
    - @emplprojs.each do |emplproj|
      %tr
        %td= emplproj.empl
        %td= emplproj.project
        %td= link_to 'Show', emplproj
        %td= link_to 'Edit', edit_emplproj_path(emplproj)
        %td= link_to 'Destroy', emplproj, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Emplproj', new_emplproj_path

app/views/emplprojs/new.html.haml
%h1 New emplproj

= render 'form'

= link_to 'Back', emplprojs_path

app/views/emplprojs/show.html.haml
%p#notice= notice

%p
  %b Empl:
  = @emplproj.empl
%p
  %b Project:
  = @emplproj.project

= link_to 'Edit', edit_emplproj_path(@emplproj)
\|
= link_to 'Back', emplprojs_path