config/routes.rb
Rails.application.routes.draw do
  resources :emplprojs
  resources :projects do
    member do
      get :activate
    end
  end
  resources :empls do
    collection do
      get :search
    end
    member do
      get :change_depart
    end
  end
 
  resources :departs
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/views/roles/edit.html.haml
=breadcrumb_tag do
  %li
    Администрирование
  %li
    = link_to 'Роли', roles_path
  %li
    = link_to(@role.name, @role)  
  %li.active
    = t('headers.roles.edit')

.page-header
  %h1= t('headers.roles.edit')

= render 'form'

app/views/roles/index.html.haml
=breadcrumb_tag do
  %li.active
    Роли
  %li
    Администрирование

.page-header
  %h1= t('headers.roles.index')

%table.table.table-hover.table-striped
  %caption
    = link_to new_role_path, class: 'btn btn-success' do
      = fa_icon :plus
      = t('buttons.new.role')
  %thead
    %tr
      %th= Role.human_attribute_name(:name)
      %th= Role.human_attribute_name(:info)
      %th= Role.human_attribute_name(:full_info)
      %th

  %tbody
    - @roles.each do |role|
      %tr
        %td{:data => Role.human_attribute_name(:name)}= role.name
        %td{:data => Role.human_attribute_name(:info)}= role.info
        %td{:data => Role.human_attribute_name(:full_info)}= role.full_info
        %td.right
          = link_to role, class: 'btn btn-warning' do
            = fa_icon :eye
            = t('buttons.show')
          = link_to edit_role_path(role), class: 'btn btn-info' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to role, :method => :delete, 
          :data => { :confirm => t('buttons.confirm.role') }, 
          class: 'btn btn-danger' do
            = fa_icon :times
            = t('buttons.destroy')

app/views/roles/new.html.haml
=breadcrumb_tag do
  %li
    Администрирование
  %li
    = link_to 'Роли', roles_path
  %li.active
    = t('headers.roles.new')

.page-header
  %h1= t('headers.roles.new')

= render 'form'