config/routes.rb
Rails.application.routes.draw do
  resources :emplprojs
  resources :projects do
    member do
      get :activate
    end
  end
  resources :empls do
    collection do
      get :search
    end
    member do
      get :change_depart
    end
  end
 
  resources :departs
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/empl.rb
class Empl < ActiveRecord::Base
  belongs_to :depart

  has_many :emplprojs, inverse_of: :empl
  

  validates :last_name, length: {maximum: 20}, presence: true
  validates :first_name, length: {maximum: 10}, presence: true
  validates :second_name, length: {maximum: 20}, presence: true
  validates :birthday, presence: true
  validates :post, presence: true
  validates :inn, length: {is: 7}, presence: true, numericality:
{only_integer: true}, uniqueness: true
  validates :passport, length: {is: 10},  presence: true, numericality:
{only_integer: true}, uniqueness: true
  validates :depart, presence: true
  accepts_nested_attributes_for :depart, reject_if: :all_blank


  def self.search(params)
    result = Empl.eager_load(:depart, :emplprojs, emplprojs: :project).references(:depart)
    if params['project_id'].present?
      result = result.where("emplprojs.project_id = ?", params['project_id'])
    end
    if params['depart_id'].present?
      result = result.where(depart_id: params['depart_id'])
    end
    if params['last_name'].present?
      result = result.where(last_name: params['last_name'])
    end
    if params['first_name'].present?
      result = result.where(first_name: params['first_name'])
    end
    if params['second_name'].present?
      result = result.where(second_name: params['second_name'])
    end
    if params['birthday'].present?
      result = result.where(birthday: params['birthday'])
    end
    if params['post'].present?
      result = result.where(post: params['post'])
    end
    if params['inn'].present?
      result = result.where(inn: params['inn'])
    end
     if params['passport'].present?
      result = result.where(passport: params['passport'])
    end
     result.all
  end
  
  



end

app/controllers/empls_controller.rb
class EmplsController < ApplicationController
  before_action :set_empl, only: [:show, :edit, :update, :destroy, :change_depart]
  skip_before_action :check_ctr_auth, only: [:new, :create]
  skip_before_filter :require_login, :only => [:new, :create]




  # GET /empls
  # GET /empls.json
  def index
    @empls = Empl.page params[:page]
  end

  def search
    if params.has_key?('search')
      @empls = Empl.search(params['search'])
    else
      @empls = []
    end
    params['search'] ||= {}
  end

  # GET /empls/1
  # GET /empls/1.json
  def show
  end

  # GET /empls/new
  def new
    @empl = Empl.new
    @empl.build_depart
  end

  # GET /empls/1/edit
  def edit
  end

  # POST /empls
  # POST /empls.json
  def create
    @empl = Empl.new(empl_params)

    respond_to do |format|
      if @empl.save
        format.html { redirect_to @empl, notice: 'Empl was successfully created.' }
        format.json { render :show, status: :created, location: @empl }
      else
        format.html { render :new }
        format.json { render json: @empl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empls/1
  # PATCH/PUT /empls/1.json
  def update
    respond_to do |format|
      if @empl.update(empl_params)
        format.html { redirect_to @empl, notice: 'Empl was successfully updated.' }
        format.json { render :show, status: :ok, location: @empl }
      else
        format.html { render :edit }
        format.json { render json: @empl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empls/1
  # DELETE /empls/1.json
  def destroy
    @empl.destroy
    respond_to do |format|
      format.html { redirect_to empls_url, notice: 'Empl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def change_depart
    @empl.depart = Depart.find_by_id(params[:empl][:depart_id])
    respond_to do |f|
      if @empl.save
        f.html { redirect_to @empl, notice: 'Сотрудник изменен.' }
        f.json { render :show, status: :ok, location: @empl }
      else
        r.depart = depart; r.save
        f.html { render :edit }
        f.json { render json: @empl.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empl
      @empl = Empl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empl_params
      params.require(:empl).permit(:last_name, :first_name, :second_name, :birthday, :passport, :inn, :post, :depart_id,
      depart_attributes: [:id, :_destroy, :d_name])
    end
    def check_ctr_auth()
      case action_name.to_sym
      when :show
        if @current_role_user.try(:is_admin?)
          return true
        end
        if @current_role_user.try(:is_operator?)
          return true
        end
      when :index
        if @current_role_user.try(:is_admin?)
          return true
        end
        if @current_role_user.try(:is_operator?)
          return true
        end
      when :new
        if @current_role_user.try(:is_admin?)
          return true
        end
        if @current_role_user.try(:is_operator?)
          return false
        end
      when :create
        if @current_role_user.try(:is_admin?)
          return true
        end
        if @current_role_user.try(:is_operator?)
          return false
        end
      when :edit
        if @current_role_user.try(:is_operator?)
          return false
        end
        if @current_role_user.try(:is_admin?)
          return true
        end
      when :destroy
        if @current_role_user.try(:is_operator?)
          return false
        end
        if @current_role_user.try(:is_admin?)
          return true
        end
      when :search
        if @current_role_user.try(:is_operator?)
          return true
        end
        if @current_role_user.try(:is_admin?)
          return true
        end
      else
        if @current_role_user.try(:is_operator?)
          return false
        end
        if @current_role_user.try(:is_admin?)
          return true
        end
      end
    end
end

app/helpers/empls_helper.rb
module EmplsHelper
  def empl_options()
    Empl.all.pluck('id')
  end
  def depart_for_select
    Depart.all.collect {|p| [p.d_name, p.id]}
  end
  
end

app/views/empls/_change_depart.html.haml
%h3 Изменить отдел на существующий
= form_for @empl, url: change_depart_empl_path(@empl), method: :get do |c|
  .row
    .col-md-6
      .form-group
        = c.label :depart
        = c.select :depart_id, Depart.all.map{|ct| [ct.d_name, ct.id]},
          {}, {class: 'form-control'}
        = c.error_messages_for(:depart_id)
  .form-actions
    = c.submit nil, class: 'btn btn-primary'

app/views/empls/_depart_form.html.haml
.col-md-6
  %div{class: 'panel panel-'+ (i==1 ? 'success' : 'info')}
    .panel-heading
      -if i==1
        Редактирование отдела
      -else
        Новый отдел
      .clearfix
    .panel-body
      .row
        .col-md-6
          .form-group
            = fr.label :d_name
            = fr.text_field :d_name, class: 'form-control'
            = fr.error_messages_for(:d_name)

app/views/empls/_form.html.haml
= form_for @empl do |f|
  = error_messages_for @empl
  .row
  .form-actions.bottom10
    = f.submit nil, class: 'btn btn-primary'
  .row
    .col-md-6
      .form-group
        = f.label :last_name
        = f.text_field :last_name, placeholder: "Введите фамилию", class: 'form-control'
        = f.error_messages_for(:last_name)
  .row
    .col-md-6
      .form-group
        = f.label :first_name
        = f.text_field :first_name, placeholder: "Введите имя", class: 'form-control'
        = f.error_messages_for(:first_name)
  .row
    .col-md-6
      .form-group
        = f.label :second_name
        = f.text_field :second_name, placeholder: "Введите отчество", class: 'form-control'
        = f.error_messages_for(:second_name)
  .row
    .col-md-6
      .form-group
        = f.label :birthday
        .input-group.date.datepicker
          = f.text_field(:birthday, value: lnil(f.object.birthday), placeholder: "Выберите дату рождения",
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:birthday)
  .row
    .col-md-6
      .form-group
        = f.label :passport
        = f.text_field :passport, placeholder: "Введите данные паспорта", class: 'form-control'
        = f.error_messages_for(:passport)
  .row
    .col-md-6
      .form-group
        = f.label :inn
        = f.text_field :inn, placeholder: "Введите данные инн", class: 'form-control'
        = f.error_messages_for(:inn)
  .row
    .col-md-6
      .form-group
        = f.label :post
        = f.text_field :post, placeholder: "Введите название должности", class: 'form-control'
        = f.error_messages_for(:post)
  .row
  - if @empl.new_record?
    .row
      .col-md-6
        .form-group
        = f.label :depart
        = f.select :depart_id, Depart.all.map{|x| [x.d_name, x.id]},
            {:include_blank => 'Выбрать отдел'}, {class: 'form-control'}
        = f.error_messages_for(:depart_id)
    .row
      .col-md-13
        .form-group
        = link_to_add_depart(f)
  - else
    .row
      .col-md-13
        .form-group
        = f.fields_for(:depart) do |fr|
          = fr.hidden_field(:id)
          = render('empls/depart_form', fr: fr, i: 1) 
  
      

app/views/empls/edit.html.haml
=breadcrumb_tag do
  %li
    Сотрудники
  %li
    = link_to 'Сотрудники', empls_path
  %li.active
    = t('headers.empls.Редактирование сотрудника')
  %li
    Администрирование

.page-header
  %h1= t('headers.empls.Редактирование сотрудника')
= link_to  projects_path, class: 'btn btn-warning' do
  = t('buttons.Назад')

= render 'form'

%h3 Выбор другого отдела
= form_for @empl, url: change_depart_empl_path(@empl), method: :get do |f|
  .row
    .col-md-6
      .form-group
        = f.label :depart
        = f.select :depart_id, Depart.all.map{|x| [x.d_name, x.id]},
          {}, {class: 'form-control'}
        = f.error_messages_for(:depart_id)
       
  

app/views/empls/index.html.haml
=breadcrumb_tag do
  %li.active
    Сотрудники
  %li
    = link_to 'Сорудники', empls_path
  %li
    Администрирование

.page-header
  %h1= t('headers.empls.Список сотрудников')

.table-responsive
  %table.table.table-hover.table-striped.table-condensed
    %caption
      = link_to new_empl_path, class: 'btn btn-success' do
        = fa_icon :plus
        = t('buttons.new.empl')
    %thead
      %tr
        %th= Empl.human_attribute_name(:last_name)
        %th= Empl.human_attribute_name(:first_name)
        %th= Empl.human_attribute_name(:second_name)
        %th= Empl.human_attribute_name(:birthday)
        %th= Empl.human_attribute_name(:passport)
        %th= Empl.human_attribute_name(:inn)
        %th= Empl.human_attribute_name(:post)
        %th= Empl.human_attribute_name(:depart)
        %th
    %tbody
      - @empls.each do |empl|
        %tr
          %td{:data => Empl.human_attribute_name(:last_name)}= empl.last_name
          %td{:data => Empl.human_attribute_name(:first_name)}= empl.first_name
          %td{:data => Empl.human_attribute_name(:second_name)}= empl.second_name
          %td{:data => Empl.human_attribute_name(:birthday)}= empl.birthday
          %td{:data => Empl.human_attribute_name(:passport)}= empl.passport
          %td{:data => Empl.human_attribute_name(:inn)}= empl.inn
          %td{:data => Empl.human_attribute_name(:post)}= empl.post
          %td{:data => Empl.human_attribute_name(:depart)}= empl.depart.d_name
          %td.right
            = link_to empl, class: 'btn btn-warning' do
              = fa_icon :eye
              = t('buttons.show')
              = link_to edit_empl_path(empl), class: 'btn btn-info' do
                = fa_icon :edit
                = t('buttons.edit')
              = link_to empl, :method => :delete,
                :data => { :confirm => t('buttons.confirm.empl') },
                class: 'btn btn-danger' do
                = fa_icon :times
                = t('buttons.destroy')

app/views/empls/new.html.haml
=breadcrumb_tag do
  %li
    Cотрудники
  %li
    = link_to 'Сотрудники', empls_path
  %li.active
    = t('headers.empls.Новый сотрудник')
  %li
    Администрирование

.page-header
  %h1= t('headers.empls.Новый сотрудник')
= link_to  empls_path, class: 'btn btn-warning' do
  = t('buttons.Назад')

= render 'form'

app/views/empls/search.html.haml
=breadcrumb_tag do
  %li.active
    = link_to 'Сотрудники', empls_path
  %li.active
    = link_to 'Поиск', search_empls_path
  %li
    = t('headers.empls.Поиск')
  %li
    Администрирование

.page-header
  %h1= t('headers.empls.Поиск')


.container
  = form_tag(search_empls_path(), :method => "get") do
    .row
    = link_to empls_path, class: 'btn btn-warning' do
      = t('buttons.Вернуться на страницу сотрудников')
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Фамилия:"
          = text_field_tag 'search[last_name]', params['search']['last_name'], placeholder: "Введите фамилию", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Имя:"
          = text_field_tag 'search[first_name]', params['search']['first_name'], placeholder: "Введите имя", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Отчество:"
          = text_field_tag 'search[second_name]', params['search']['second_name'], placeholder: "Введите отчество", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Дата рождения:"
          = text_field_tag 'search[birthday]', params['search']['birthday'], placeholder: "Введите дату рождения в виде 01-12-1995", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Должность:"
          = text_field_tag 'search[post]', params['search']['post'], placeholder: "Введите должность", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "ИНН:"
          = text_field_tag 'search[inn]', params['search']['inn'], placeholder: "Введите инн", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Серия и номер паспорта:"
          = text_field_tag 'search[passport]', params['search']['passport'], placeholder: "Введите серию и номер пасспорта(слитно)", class: 'form-control'
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Проекты:"
          = select_tag('search[project_id]' , options_for_select(project_options(),), {include_blank: true, class: 'form-control'})
     
    .row
      .col-md-5
        .form-group
          = label_tag 'search', "Отдел:"
          = select_tag('search[depart_id]' , options_for_select(depart_for_select(), ), {include_blank: true, class: 'form-control'})
    
    = submit_tag(:search_button, value: 'Поиск', class: 'btn btn-default')
    = link_to search_empls_path, class: 'btn btn-warning' do
      = t('buttons.Очистить')
    = link_to root_path, class: "btn btn-primary" do
      = t('buttons.Вернуться на главную страницу')
  
  %dl.dl-horizontal
  - @empls.each do |empl|
    .row
      .col-md-9
        %dt
          %h3= t('headers.empl.Результат поиска')
        %dd
        %ul
          %li
            = Empl.human_attribute_name(:last_name) + ":"
            = empl.last_name
        %ul
          %li
            = Empl.human_attribute_name(:first_name) + ":"
            = empl.first_name
        %ul
          %li
            = Empl.human_attribute_name(:second_name) + ":"
            = empl.second_name
        %ul
          %li
            = Empl.human_attribute_name(:birthday) + ":"
            = empl.birthday
        %ul
          %li
            = Empl.human_attribute_name(:post) + ":"
            = empl.post
        %ul
          %li
            = Empl.human_attribute_name(:inn) + ":"
            = empl.inn
        %ul
          %li
            = Empl.human_attribute_name(:passport) + ":"
            = empl.passport
        %ul
          %li
            = Depart.human_attribute_name(:Отдел) + ":"
            = empl.depart.d_name
    .row   
      = link_to empl, class: 'btn btn-info' do
        = fa_icon "eye"
        = t('buttons.show')
    
    

app/views/empls/show.html.haml
=breadcrumb_tag do
  %li
    Сотрудники
  %li
    %li.active
    = link_to t('headers.empl.Поиск'), search_empls_path()
  %li
    = @empl.id
  %li
    Администрирование

.container
  .row
    .col-md-10
      .panel.panel-default
        .panel-heading
        .list-group
          %p.list-group-item
            %b Фамилия:
            = @empl.last_name
          %p.list-group-item
            %b Имя: 
            = @empl.first_name
          %p.list-group-item
            %b Отчество:
            = @empl.second_name
          %p.list-group-item
            %b Пасспорт:
            = @empl.passport
          %p.list-group-item
            %b Инн:
            = @empl.inn
          %p.list-group-item
            %b Должность: 
            =  @empl.post
          %p.list-group-item
            %b Отдел:
            = @empl.depart.try(:d_name)
        .panel-body
          = link_to  edit_empl_path(@empl), class: 'btn btn-primary' do
            = fa_icon :edit
            = t('buttons.edit')
          = link_to  empls_path, class: 'btn btn-warning' do
            = t('buttons.Назад')
         